### ISSUE TITLE
JDK6 and JDK7 Versions

### ISSUE THREAD

**Issue by drewoko** [radekpakula/pdf-viewr-addon#1]
Good day, Sir.

Is it possible to have version of your plugin for JDK6 and JDK7 in repository? Because it currently builded only for Java8.

Thank you!

**Comment by radekpakula** [comment]
Hi
You can fork my work and made you own change with project properties. 
You can also create a new widget based on my code and insert it into the official repository Vaadin if you wish. On official addon page i can only change the version of vaadin for new widget revision but not a jdk. 

Greetings
