### ISSUE TITLE
Pdf-Viewer doesn't show pdf

### ISSUE THREAD

**Issue by nimakro** [radekpakula/pdf-viewr-addon#2]
Hey radekpakula,
I tried to use your Addon in my project. I generated PDF and pass it to your PDF-Viewer as a `StreamResource`. 
I used the code snipped from your Github-Page

```java
StreamResource streamResource = getStreamResource();
streamResource.setMIMEType("application/pdf");
PdfViewer c = new PdfViewer(streamResource);
c.setPage(0);
c.setSizeFull();
c.setVisible(true);
// layout is a Css-Layout
layout.addComponent(c);
```
Then I get the following result:
![image](https://cloud.githubusercontent.com/assets/21091608/21656958/985e00a6-d2c0-11e6-8a71-a642b3ff883c.png)

saying that there are 0 Pages.
It seems that `getStream()` in the `StreamResource` is never called from the PdfView.
Is this a Bug? Or em I missing something.

Regards micah

**Comment by radekpakula** [comment]
It looks like you pdf file is not loaded properly or is defective. Try with
another file or sample pdf from the web and check if is work. If not debug
your page in web-browser like chrome or firefox and check if Js-script for
this addon is loaded. You can also check javascript console.

I see that widgetsets for this addon is not compiled properly on your side
because css is broken.

Regards Radek

**Comment by nimakro** [comment]
Mhm thanks for your reply,
I checked in the Browser console and I see an error that it can't find the pdf.work.js file.
It is looking for the file at `APP/PUBLISHED/pdf.worker.js`
So I think you are right, the widgetset is not compiled right.

I use spring-boot to run my projekt.
I did run  `mvn clean vaadin:update-widgetset package`
But for some reason, the pdf.worker.js file is not copied to the right directory.

I created another small vaadin project without spring and there the addon works perfectly fine.
Any idea on what spring-boot is doing differently.

Regards Micah

**Comment by radekpakula** [comment]
run mvn clean vaadin:compile and check again or tray compile with eclipse
plugin for vaadin

I have default pom for vaadin project

Radek
5 sty 2017 22:49, "nimakro" <notifications@github.com> napisał(a):

**Comment by nimakro** [comment]
Hay radekpakula,

I figured it out the issue. It's because I am using spring-boot with Vaadin.
Your plugin is looking for the javascript resources under the following path: `APP/PUBLISHED/pdf.worker.js'` (VPDFViewer Line:151)
and spring-boot is publishing them under a different static path and that's the reason why the plugin is not working correctly in my case.

Thanks for your help

Regards Micah

**Comment by Bemat** [comment]
nimakro, I have the same issue. How do you solved it?
Thanks for your help!

Matteo

**Comment by nimakro** [comment]
Hey @Bemat well, since the javascript resource paths are hardcoded and spring boot is using a different file structure, I didn't get it to work. I ended up writing my own `AbstractJavaScriptComponent ` and used PDF.js and PDF.Worker.js directly.

**Comment by deen13** [comment]
For those who are still struggling with the problem: I found a hacky workaround.
Since the addon tries to load a JS library from the localhost, which is not available at that point, this request can be forwarded to the right address via a Spring Controller.


```java
@Controller
public class PdfJsRedirectController {

	@RequestMapping(value = "/APP/PUBLISHED/pdf.worker.js")
	public String forwardWorkerJsRequestToVaadin() {
		return "forward:/vaadinServlet/APP/PUBLISHED/pdf.worker.js";
	}

}
```

rel: https://stackoverflow.com/a/45331984
