### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by amgdark** [radekpakula/pdf-viewr-addon#3]
Hello radekpakula, i am trying to implement a project with you add on (PdfViewer), so, when i compile get a error:

Failed to execute goal com.vaadin:vaadin-maven-plugin:8.0.3:compile (default-cli) on project myapplication: GWT Module pl.pdfviewer.WidgetSet not found in project sources or resources. 

Can you help me, thanks in advance

**Comment by radekpakula** [comment]
Hi
Checkout version 1.2.2. I added the missing file pl.pdfviewer.WidgetSet and scss.
Please check and give me feedback

**Comment by amgdark** [comment]
Thanks, it worked!!! Regards
