### ISSUE TITLE
Missing required attribute: groupId

### ISSUE THREAD

**Issue by zlaval** [radekpakula/pdf-viewr-addon#4]
I try to use the addon with gradle. When it was added as a dependency:
compile group: 'pl.pdfviewer', name: 'pdfviewer', version: '1.3.1'

I'v got the following error message on gradle build:
Error:Missing required attribute: groupId

**Comment by radekpakula** [comment]
Added missing attribute 'groupId' in auto generated pom.
Try version 1.3.2

**Comment by zlaval** [comment]
groupId missing in 1.3.2 too.
...
<modelVersion>4.0.0</modelVersion>
<artifactId>pdfviewer</artifactId>
<packaging>jar</packaging>
<version>1.3.2</version>
<name>PdfViewer addon</name>
...

Could not resolve pl.pdfviewer:pdfviewer:1.3.2.
         > Could not parse POM http://maven.vaadin.com/vaadin-addons/pl/pdfviewer/pdfviewer/1.3.2/pdfviewer-1.3.2.pom
            > Missing required attribute: groupId
