### ISSUE TITLE
groupId missing in 1.3.2 too.

### ISSUE THREAD

**Issue by zlaval** [radekpakula/pdf-viewr-addon#5]
groupId missing in 1.3.2 too.
...
4.0.0
pdfviewer
jar
1.3.2
PdfViewer addon
...

Could not resolve pl.pdfviewer:pdfviewer:1.3.2.
> Could not parse POM http://maven.vaadin.com/vaadin-addons/pl/pdfviewer/pdfviewer/1.3.2/pdfviewer-1.3.2.pom
> Missing required attribute: groupId

**Comment by radekpakula** [comment]
@zlaval thank you for noticing this issue. My mistake.  tray version 1.3.3

[maven.vaadin.com/vaadin-addons/pl/pdfviewer/pdfviewer/1.3.3/pdfviewer-1.3.3.pom](url)
