### ISSUE TITLE
Unable to find version 1.3.3 on Maven repositories

### ISSUE THREAD

**Issue by javydreamercsw** [radekpakula/pdf-viewr-addon#6]
I've tried a few times, days apart, and still can't resolve the dependencies.

> Failed to collect dependencies at pl.pdfviewer:pdfviewer:jar:1.3.3: Failed to read artifact descriptor for pl.pdfviewer:pdfviewer:jar:1.3.3: Could not find artifact pl.pdfviewer:pdfviewer-root:pom:1.3.3 in vaadin-addons (http://maven.vaadin.com/vaadin-addons

**Comment by zlaval** [comment]
The previous problem is resolved now, but as javydreamercsw mentioned, a new bug appeared:

Error:Could not find pl.pdfviewer:pdfviewer-root:1.3.3.

**Comment by javydreamercsw** [comment]
Glad to know I was not alone. Was surprised no one else complained about it before.

Is probably not deployed to Maven repo.

**Comment by radekpakula** [comment]
strange

I re-create this addon using new version of vaadin and addon structure. Try version 1.3.5 and give me feedback please. I hope this solution help.

**Comment by javydreamercsw** [comment]
I'll try it and report back after lunch.

**Comment by zlaval** [comment]
I've made a fast try. Dependencies seems ok now, but widget compile fail. I will debug it at night or tomorrow.

**Comment by javydreamercsw** [comment]
My project compiled fine without any errors or warnings.

**Comment by radekpakula** [comment]
Great ;] Thanks for report.
